name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose --manifest-path=rust/Cargo.toml
    - name: Run rust tests
      run: cargo test --verbose --manifest-path=rust/Cargo.toml
    - name: Download Godot Engine
      run: |
        wget https://downloads.tuxfamily.org/godotengine/4.3/Godot_v4.3-stable_linux.x86_64.zip
        unzip Godot_v4.3-stable_linux.x86_64.zip -d godot43
        chmod +x godot43/Godot_v4.3-stable_linux.x86_64
    - name: Get export templates
      run: |
        wget https://github.com/godotengine/godot/releases/download/4.3-stable/Godot_v4.3-stable_export_templates.tpz
        mv Godot_v4.3-stable_export_templates.tpz Godot_v4.3-stable_export_templates.zip
        unzip Godot_v4.3-stable_export_templates.zip
        mkdir -p /home/runner/.local/share/godot/export_templates/4.3.stable/
        mv templates/linux_debug.x86_64 /home/runner/.local/share/godot/export_templates/4.3.stable/linux_debug.x86_64
        mv templates/linux_release.x86_64 /home/runner/.local/share/godot/export_templates/4.3.stable/linux_release.x86_64
    - name: Export Godot project
      run: |
        cd godot
        ls -lth 
        ../godot43/Godot_v4.3-stable_linux.x86_64 --headless --export-debug "Linux" lidar.app
    - name: Run
      run: |
        ls -lth
        mkdir lidar_out
        godot/lidar.app --headless --n_iterations 1
